### ISSUE TITLE
`infer_devices` failing for `tp.copy`

### ISSUE THREAD

**Issue by markkraay** [NVIDIA/TensorRT-Incubator#126]
```python
>>> a = tp.Tensor([1,2], device=tp.device("gpu"))
>>> output = tp.copy(a, tp.device("cpu"))
>>> a.shape == output.shape
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tripy/tripy/frontend/utils.py", line 256, in wrapper
    return func(*new_args, **new_kwargs)
  File "/tripy/tripy/frontend/shape.py", line 163, in __eq__
    return bool(all(self.as_tensor() == other.as_tensor()))
  File "/tripy/tripy/frontend/tensor.py", line 249, in __bool__
    data = self.data().data()
  File "/tripy/tripy/frontend/tensor.py", line 218, in data
    arr = self.eval()
  File "/tripy/tripy/frontend/tensor.py", line 195, in eval
    trace = Trace([self])
  File "/tripy/tripy/frontend/trace/trace.py", line 102, in __init__
    self._infer_tensor_info()
  File "/tripy/tripy/frontend/trace/trace.py", line 44, in _infer_tensor_info
    op.infer_devices()
  File "/tripy/tripy/frontend/trace/ops/base.py", line 158, in infer_devices
    self.inputs and len(self.outputs) == 1 and all(inp.device == self.inputs[0].device for inp in self.inputs)
AssertionError: Default implementation cannot handle cases where there are no inputs, multiple outputs, or multiple inputs with different devices. Please override.
```

**Comment by yizhuoz004** [comment]
`a.shape` is on gpu while `out.shape` is on cpu, so the error is expected because binary elementwise op cannot operate between different devices. I think we should update the error message to be "Inputs are not on the same device" etc.

**Comment by markkraay** [comment]
@yizhuoz004 It seems like some binary element-wise operations actually work between different devices.
```python
>>> a = tp.Tensor([1], device=tp.device("gpu"))
>>> b = tp.Tensor([2], device=tp.device("cpu"))
>>> print(a.device, b.device)
gpu:0 cpu:0
>>> a + b
tensor([3], dtype=int32, loc=gpu:0, shape=(1,))
```

**Comment by yizhuoz004** [comment]
> @yizhuoz004 It seems like some binary element-wise operations actually work between different devices.
> 
> ```python
> >>> a = tp.Tensor([1], device=tp.device("gpu"))
> >>> b = tp.Tensor([2], device=tp.device("cpu"))
> >>> print(a.device, b.device)
> gpu:0 cpu:0
> >>> a + b
> tensor([3], dtype=int32, loc=gpu:0, shape=(1,))
> >>> a == b
> tensor([False], dtype=bool, loc=gpu:0, shape=(1,))
> ```

This is a long standing issue of `device`, `a` will be on device after evaluation because MLIR-TRT can only return on device.
