### ISSUE TITLE
'tensorrt.shuffle' op operand #0 must be a tensor of allowed TensorRT element types, but got 'tensor<2x3x2xi1>

### ISSUE THREAD

**Issue by markkraay** [NVIDIA/TensorRT-Incubator#127]
```python
>>> a = tp.iota((3,3,2))
>>> indices = tp.Tensor([0,2], dtype=tp.int32)
>>> out = tp.gather(a, 1, indices)
>>> out == tp.ones((3,2,2))
==== Trace IR ====
t0 = storage(data=[3, 3, 2], shape=(3,), dtype=int32, device=gpu:0)
t2 = iota(t0, dim=0, output_rank=3, dtype=float32)
t3 = storage(data=[0, 2], shape=(2,), dtype=int32, device=gpu:0)
t5 = gather(t2, t3, axis=1)
t22 = storage(data=[3, 2, 2], shape=(3,), dtype=int32, device=gpu:0)
t24 = fill(t22, value=1, output_rank=3, dtype=float32)
t25 = t5 == t24
outputs:
    t25: [rank=(3), dtype=(bool), loc=(gpu:0)]

==== Flat IR ====
t0: [rank=(1), shape=((3,)), dtype=(int32), loc=(gpu:0)] = ConstantOp(data=[3, 3, 2])
t2: [rank=(3), dtype=(float32), loc=(gpu:0)] = DynamicIotaOp(t0, dim=0)
t3: [rank=(1), shape=((2,)), dtype=(int32), loc=(gpu:0)] = ConstantOp(data=[0, 2])
t_inter9: [rank=(0), shape=(()), dtype=(int32), loc=(gpu:0)] = GetDimensionSizeOp(t2, dim=0)
t_inter10: [rank=(1), shape=([1]), dtype=(int32), loc=(<class 'tripy.common.device.device'>)] = ConstantOp(data=[1])
t_inter8: [rank=(1), shape=((1,)), dtype=(int32), loc=(gpu:0)] = DynamicReshapeOp(t_inter9, t_inter10)
t_inter12: [rank=(0), shape=(()), dtype=(int32), loc=(gpu:0)] = GetDimensionSizeOp(t2, dim=1)
t_inter13: [rank=(1), shape=([1]), dtype=(int32), loc=(<class 'tripy.common.device.device'>)] = ConstantOp(data=[1])
t_inter11: [rank=(1), shape=((1,)), dtype=(int32), loc=(gpu:0)] = DynamicReshapeOp(t_inter12, t_inter13)
t_inter15: [rank=(0), shape=(()), dtype=(int32), loc=(gpu:0)] = GetDimensionSizeOp(t2, dim=2)
t_inter16: [rank=(1), shape=([1]), dtype=(int32), loc=(<class 'tripy.common.device.device'>)] = ConstantOp(data=[1])
t_inter14: [rank=(1), shape=((1,)), dtype=(int32), loc=(gpu:0)] = DynamicReshapeOp(t_inter15, t_inter16)
t_inter7: [rank=(1), dtype=(int32), loc=(gpu:0)] = ConcatenateOp(t_inter8, t_inter11, t_inter14, dim=0)
t_inter17: [rank=(1), shape=([1]), dtype=(int32), loc=(<class 'tripy.common.device.device'>)] = ConstantOp(data=[0])
t_inter18: [rank=(1), shape=([1]), dtype=(int32), loc=(<class 'tripy.common.device.device'>)] = ConstantOp(data=[1])
t_inter19: [rank=(1), shape=([1]), dtype=(int32), loc=(<class 'tripy.common.device.device'>)] = ConstantOp(data=[1])
t_inter6: [rank=(1), shape=([1]), dtype=(int32), loc=(gpu:0)] = DynamicSliceOp(t_inter7, t_inter17, t_inter18, t_inter19)
t_inter21: [rank=(1), shape=([1]), dtype=(int32), loc=(<class 'tripy.common.device.device'>)] = ConstantOp(data=[2])
t_inter22: [rank=(1), shape=([1]), dtype=(int32), loc=(<class 'tripy.common.device.device'>)] = ConstantOp(data=[3])
t_inter20: [rank=(1), dtype=(int32), loc=(gpu:0)] = DynamicSliceOp(t_inter7, t_inter21, t_inter22, t_inter19)
t_inter5: [rank=(1), dtype=(int32), loc=(gpu:0)] = ConcatenateOp(t_inter6, t_inter19, t_inter20, dim=0)
t5: [rank=(3), dtype=(float32), loc=(gpu:0)] = DynamicGatherOp(t2, t3, t_inter5, axis=1)
t22: [rank=(1), shape=((3,)), dtype=(int32), loc=(gpu:0)] = ConstantOp(data=[3, 2, 2])
t_inter25: [rank=(0), shape=(()), dtype=(float32), loc=(gpu:0)] = ConstantOp(data=1)
t24: [rank=(3), dtype=(float32), loc=(gpu:0)] = DynamicBroadcastOp(t_inter25, t22, broadcast_dim=[])
t_inter31: [rank=(0), shape=(()), dtype=(int32), loc=(gpu:0)] = GetDimensionSizeOp(t5, dim=0)
t_inter32: [rank=(1), shape=([1]), dtype=(int32), loc=(<class 'tripy.common.device.device'>)] = ConstantOp(data=[1])
t_inter30: [rank=(1), shape=((1,)), dtype=(int32), loc=(gpu:0)] = DynamicReshapeOp(t_inter31, t_inter32)
t_inter34: [rank=(0), shape=(()), dtype=(int32), loc=(gpu:0)] = GetDimensionSizeOp(t5, dim=1)
t_inter35: [rank=(1), shape=([1]), dtype=(int32), loc=(<class 'tripy.common.device.device'>)] = ConstantOp(data=[1])
t_inter33: [rank=(1), shape=((1,)), dtype=(int32), loc=(gpu:0)] = DynamicReshapeOp(t_inter34, t_inter35)
t_inter37: [rank=(0), shape=(()), dtype=(int32), loc=(gpu:0)] = GetDimensionSizeOp(t5, dim=2)
t_inter38: [rank=(1), shape=([1]), dtype=(int32), loc=(<class 'tripy.common.device.device'>)] = ConstantOp(data=[1])
t_inter36: [rank=(1), shape=((1,)), dtype=(int32), loc=(gpu:0)] = DynamicReshapeOp(t_inter37, t_inter38)
t_inter29: [rank=(1), dtype=(int32), loc=(gpu:0)] = ConcatenateOp(t_inter30, t_inter33, t_inter36, dim=0)
t_inter39: [rank=(1), shape=([3]), dtype=(int32), loc=(<class 'tripy.common.device.device'>)] = ConstantOp(data=[1, 1, 1])
t_inter28: [rank=(1), shape=([3]), dtype=(bool), loc=(gpu:0)] = CompareOp.EQ(t_inter29, t_inter39, compare_direction='EQ')
t_inter42: [rank=(0), shape=(()), dtype=(int32), loc=(gpu:0)] = GetDimensionSizeOp(t24, dim=0)
t_inter43: [rank=(1), shape=([1]), dtype=(int32), loc=(<class 'tripy.common.device.device'>)] = ConstantOp(data=[1])
t_inter41: [rank=(1), shape=((1,)), dtype=(int32), loc=(gpu:0)] = DynamicReshapeOp(t_inter42, t_inter43)
t_inter45: [rank=(0), shape=(()), dtype=(int32), loc=(gpu:0)] = GetDimensionSizeOp(t24, dim=1)
t_inter46: [rank=(1), shape=([1]), dtype=(int32), loc=(<class 'tripy.common.device.device'>)] = ConstantOp(data=[1])
t_inter44: [rank=(1), shape=((1,)), dtype=(int32), loc=(gpu:0)] = DynamicReshapeOp(t_inter45, t_inter46)
t_inter48: [rank=(0), shape=(()), dtype=(int32), loc=(gpu:0)] = GetDimensionSizeOp(t24, dim=2)
t_inter49: [rank=(1), shape=([1]), dtype=(int32), loc=(<class 'tripy.common.device.device'>)] = ConstantOp(data=[1])
t_inter47: [rank=(1), shape=((1,)), dtype=(int32), loc=(gpu:0)] = DynamicReshapeOp(t_inter48, t_inter49)
t_inter40: [rank=(1), dtype=(int32), loc=(gpu:0)] = ConcatenateOp(t_inter41, t_inter44, t_inter47, dim=0)
t_inter27: [rank=(1), shape=([3]), dtype=(int32), loc=(gpu:0)] = SelectOp(t_inter28, t_inter40, t_inter29)
t_inter26: [rank=(3), dtype=(float32), loc=(gpu:0)] = DynamicBroadcastOp(t5, t_inter27, broadcast_dim=[0, 1, 2])
t_inter50: [rank=(3), dtype=(float32), loc=(gpu:0)] = DynamicBroadcastOp(t24, t_inter27, broadcast_dim=[0, 1, 2])
t25: [rank=(3), dtype=(bool), loc=(gpu:0)] = CompareOp.EQ(t_inter26, t_inter50, compare_direction='EQ')
outputs:
    t25: [rank=(3), dtype=(bool), loc=(gpu:0)]

==== MLIR ====
module @outs_t25_5 {
  func.func @main() -> tensor<?x?x?xi1> {
    %c = stablehlo.constant dense<[3, 3, 2]> : tensor<3xi32>
    %0 = stablehlo.dynamic_iota %c, dim = 0 : (tensor<3xi32>) -> tensor<?x?x?xf32>
    %c_0 = stablehlo.constant dense<[0, 2]> : tensor<2xi32>
    %1 = stablehlo.get_dimension_size %0, dim = 0 : (tensor<?x?x?xf32>) -> tensor<i32>
    %c_1 = stablehlo.constant dense<1> : tensor<1xi32>
    %2 = stablehlo.reshape %1 : (tensor<i32>) -> tensor<1xi32>
    %3 = stablehlo.get_dimension_size %0, dim = 1 : (tensor<?x?x?xf32>) -> tensor<i32>
    %c_2 = stablehlo.constant dense<1> : tensor<1xi32>
    %4 = stablehlo.reshape %3 : (tensor<i32>) -> tensor<1xi32>
    %5 = stablehlo.get_dimension_size %0, dim = 2 : (tensor<?x?x?xf32>) -> tensor<i32>
    %c_3 = stablehlo.constant dense<1> : tensor<1xi32>
    %6 = stablehlo.reshape %5 : (tensor<i32>) -> tensor<1xi32>
    %7 = stablehlo.concatenate %2, %4, %6, dim = 0 : (tensor<1xi32>, tensor<1xi32>, tensor<1xi32>) -> tensor<3xi32>
    %c_4 = stablehlo.constant dense<0> : tensor<1xi32>
    %c_5 = stablehlo.constant dense<1> : tensor<1xi32>
    %c_6 = stablehlo.constant dense<1> : tensor<1xi32>
    %8 = stablehlo.real_dynamic_slice %7, %c_4, %c_5, %c_6 : (tensor<3xi32>, tensor<1xi32>, tensor<1xi32>, tensor<1xi32>) -> tensor<1xi32>
    %c_7 = stablehlo.constant dense<2> : tensor<1xi32>
    %c_8 = stablehlo.constant dense<3> : tensor<1xi32>
    %9 = stablehlo.real_dynamic_slice %7, %c_7, %c_8, %c_6 : (tensor<3xi32>, tensor<1xi32>, tensor<1xi32>, tensor<1xi32>) -> tensor<?xi32>
    %10 = stablehlo.concatenate %8, %c_6, %9, dim = 0 : (tensor<1xi32>, tensor<1xi32>, tensor<?xi32>) -> tensor<3xi32>
    %11 = "stablehlo.dynamic_gather"(%0, %c_0, %10) <{dimension_numbers = #stablehlo.gather<offset_dims = [0, 2], collapsed_slice_dims = [1], start_index_map = [1], index_vector_dim = 1>}> : (tensor<?x?x?xf32>, tensor<2xi32>, tensor<3xi32>) -> tensor<?x2x?xf32>
    %c_9 = stablehlo.constant dense<[3, 2, 2]> : tensor<3xi32>
    %cst = stablehlo.constant dense<1.000000e+00> : tensor<f32>
    %12 = stablehlo.dynamic_broadcast_in_dim %cst, %c_9, dims = [] : (tensor<f32>, tensor<3xi32>) -> tensor<?x?x?xf32>
    %13 = stablehlo.get_dimension_size %11, dim = 0 : (tensor<?x2x?xf32>) -> tensor<i32>
    %c_10 = stablehlo.constant dense<1> : tensor<1xi32>
    %14 = stablehlo.reshape %13 : (tensor<i32>) -> tensor<1xi32>
    %c_11 = stablehlo.constant dense<2> : tensor<i32>
    %c_12 = stablehlo.constant dense<1> : tensor<1xi32>
    %c_13 = stablehlo.constant dense<2> : tensor<1xi32>
    %15 = stablehlo.get_dimension_size %11, dim = 2 : (tensor<?x2x?xf32>) -> tensor<i32>
    %c_14 = stablehlo.constant dense<1> : tensor<1xi32>
    %16 = stablehlo.reshape %15 : (tensor<i32>) -> tensor<1xi32>
    %17 = stablehlo.concatenate %14, %c_13, %16, dim = 0 : (tensor<1xi32>, tensor<1xi32>, tensor<1xi32>) -> tensor<3xi32>
    %c_15 = stablehlo.constant dense<1> : tensor<3xi32>
    %18 = stablehlo.compare  EQ, %17, %c_15 : (tensor<3xi32>, tensor<3xi32>) -> tensor<3xi1>
    %19 = stablehlo.get_dimension_size %12, dim = 0 : (tensor<?x?x?xf32>) -> tensor<i32>
    %c_16 = stablehlo.constant dense<1> : tensor<1xi32>
    %20 = stablehlo.reshape %19 : (tensor<i32>) -> tensor<1xi32>
    %21 = stablehlo.get_dimension_size %12, dim = 1 : (tensor<?x?x?xf32>) -> tensor<i32>
    %c_17 = stablehlo.constant dense<1> : tensor<1xi32>
    %22 = stablehlo.reshape %21 : (tensor<i32>) -> tensor<1xi32>
    %23 = stablehlo.get_dimension_size %12, dim = 2 : (tensor<?x?x?xf32>) -> tensor<i32>
    %c_18 = stablehlo.constant dense<1> : tensor<1xi32>
    %24 = stablehlo.reshape %23 : (tensor<i32>) -> tensor<1xi32>
    %25 = stablehlo.concatenate %20, %22, %24, dim = 0 : (tensor<1xi32>, tensor<1xi32>, tensor<1xi32>) -> tensor<3xi32>
    %26 = stablehlo.select %18, %25, %17 : tensor<3xi1>, tensor<3xi32>
    %27 = stablehlo.dynamic_broadcast_in_dim %11, %26, dims = [0, 1, 2] : (tensor<?x2x?xf32>, tensor<3xi32>) -> tensor<?x?x?xf32>
    %28 = stablehlo.dynamic_broadcast_in_dim %12, %26, dims = [0, 1, 2] : (tensor<?x?x?xf32>, tensor<3xi32>) -> tensor<?x?x?xf32>
    %29 = stablehlo.compare  EQ, %27, %28 : (tensor<?x?x?xf32>, tensor<?x?x?xf32>) -> tensor<?x?x?xi1>
    return %29 : tensor<?x?x?xi1>
  }
}


Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tripy/tripy/frontend/tensor.py", line 228, in __repr__
    arr = self.data()
  File "/tripy/tripy/frontend/tensor.py", line 218, in data
    arr = self.eval()
  File "/tripy/tripy/frontend/tensor.py", line 200, in eval
    executable = compiler.compile(mlir, flat_ir=flat_ir)
  File "/tripy/tripy/utils/utils.py", line 73, in wrapper
    result = func(*args, **kwargs)
  File "/tripy/tripy/backend/mlir/compiler.py", line 107, in compile
    map_error_to_user_code_and_raise(flat_ir, exc, stderr.decode())
  File "/tripy/tripy/backend/mlir/utils.py", line 461, in map_error_to_user_code_and_raise
    raise_error(
  File "/tripy/tripy/common/exception.py", line 195, in raise_error
    raise TripyException(msg) from None
tripy.common.exception.TripyException: 

--> <stdin>:1 in <module>()

MTRTException: InternalError: failed to run compilation on module with symbol name: outs_t25_5

Additional context:
Traceback (most recent call last):
  File "/tripy/tripy/backend/mlir/compiler.py", line 100, in compile
    executable = compiler.compiler_stablehlo_to_executable(
mlir_tensorrt.runtime._mlir_libs._api.MTRTException: InternalError: failed to run compilation on module with symbol name: outs_t25_5
.
    (t25)error: 'tensorrt.shuffle' op operand #0 must be 0D/1D/2D/3D/4D/5D/6D/7D/8D tensor of allowed TensorRT tensor i8 element types or 32-bit signless integer or 16-bit float or 32-bit float or bfloat16 type or f8E4M3FN type values, but got 'tensor<2x3x2xi1>'

    This error occured while trying to compile the following FlatIR expression:
          |
          | t25: [rank=(3), shape=((-1, -1, -1)), dtype=(bool), loc=(gpu:0)] = CompareOp.EQ(t_inter26, t_inter50, compare_direction='EQ')
          | 


    Note: This originated from the following expression:

    --> <stdin>:1 in <module>()

    Input 0:

    --> <stdin>:1 in <module>()

    Input 1:

    --> /tripy/tripy/frontend/trace/ops/fill.py:121 in full()
          |
      121 |     return full_impl(shape, value, dtype, output_rank)
          | 

    --> /tripy/tripy/frontend/ops/tensor_initializers.py:57 in ones()
          |
       57 |     return full(shape, 1, dtype)
          |            ^^^^^^^^^^^^^^^^^^^^^ --- required from here

    Required from:
    --> <stdin>:1 in <module>()
    ```

**Comment by parthchadha** [comment]
```
>>> import tripy as tp
>>> a = tp.iota((3,3,2))
>>> indices = tp.Tensor([0,2], dtype=tp.int32)
>>> out = tp.gather(a, 1, indices)
>>> out == tp.ones((3,2,2))
tensor(
    [[[False, False],
      [False, False]],

     [[True, True],
      [True, True]],

     [[False, False],
      [False, False]]], 
    dtype=bool, loc=gpu:0, shape=(3, 2, 2))
```

Works fine, closing the issue.
