### ISSUE TITLE
Allclose no longer works with integers

### ISSUE THREAD

**Issue by Mgluhovskoi** [NVIDIA/TensorRT-Incubator#153]
After a recent rebase I noticed that allclose integer tests were failing. The error occurs during conversion from Flat IR to MLIR. 

Here is the log:

```
>>> a = tp.Tensor([1,1],tp.int32)
>>> b = tp.Tensor([1,1],tp.int32)
>>> tp.allclose(a,b)
==== Trace IR ====
t15 = storage(data=[1, 1], shape=(2,), dtype=int32, device=gpu:0)
t16 = storage(data=[1, 1], shape=(2,), dtype=int32, device=gpu:0)
t17 = t15 - t16
t18 = unaryelementwise(t17, kind=Kind.ABS)
t19 = unaryelementwise(t16, kind=Kind.ABS)
t20 = storage(data=1e-05, shape=(), dtype=int32, device=gpu:0)
t21 = t19 * t20
t22 = storage(data=1e-08, shape=(), dtype=int32, device=gpu:0)
t23 = t21 + t22
t24 = t18 <= t23
t25 = reduce(t24, dim=[0], kind=Kind.AND)
outputs:
    t25: [rank=(0), dtype=(bool), loc=(gpu:0)]

==== Flat IR ====
t15: [rank=(1), shape=((2,)), dtype=(int32), loc=(gpu:0)] = ConstantOp(data=[1, 1])
t16: [rank=(1), shape=((2,)), dtype=(int32), loc=(gpu:0)] = ConstantOp(data=[1, 1])
t_inter9: [rank=(0), shape=(()), dtype=(int32), loc=(gpu:0)] = GetDimensionSizeOp(t15, dim=0)
t_inter10: [rank=(1), shape=([1]), dtype=(int32), loc=(<class 'tripy.common.device.device'>)] = ConstantOp(data=[1])
t_inter8: [rank=(1), shape=((1,)), dtype=(int32), loc=(gpu:0)] = DynamicReshapeOp(t_inter9, t_inter10)
t_inter7: [rank=(1), dtype=(int32), loc=(gpu:0)] = ConcatenateOp(t_inter8, dim=0)
t_inter11: [rank=(1), shape=([1]), dtype=(int32), loc=(<class 'tripy.common.device.device'>)] = ConstantOp(data=[1])
t_inter6: [rank=(1), shape=([1]), dtype=(bool), loc=(gpu:0)] = CompareOp.EQ(t_inter7, t_inter11, compare_direction='EQ')
t_inter14: [rank=(0), shape=(()), dtype=(int32), loc=(gpu:0)] = GetDimensionSizeOp(t16, dim=0)
t_inter15: [rank=(1), shape=([1]), dtype=(int32), loc=(<class 'tripy.common.device.device'>)] = ConstantOp(data=[1])
t_inter13: [rank=(1), shape=((1,)), dtype=(int32), loc=(gpu:0)] = DynamicReshapeOp(t_inter14, t_inter15)
t_inter12: [rank=(1), dtype=(int32), loc=(gpu:0)] = ConcatenateOp(t_inter13, dim=0)
t_inter5: [rank=(1), shape=([1]), dtype=(int32), loc=(gpu:0)] = SelectOp(t_inter6, t_inter12, t_inter7)
t_inter4: [rank=(1), dtype=(int32), loc=(gpu:0)] = DynamicBroadcastOp(t15, t_inter5, broadcast_dim=[0])
t_inter16: [rank=(1), dtype=(int32), loc=(gpu:0)] = DynamicBroadcastOp(t16, t_inter5, broadcast_dim=[0])
t17: [rank=(1), dtype=(int32), loc=(gpu:0)] = SubtractOp(t_inter4, t_inter16)
t18: [rank=(1), dtype=(int32), loc=(gpu:0)] = AbsOp(t17)
t19: [rank=(1), dtype=(int32), loc=(gpu:0)] = AbsOp(t16)
t20: [rank=(0), shape=(()), dtype=(int32), loc=(gpu:0)] = ConstantOp(data=1e-05)
t_inter26: [rank=(0), shape=(()), dtype=(int32), loc=(gpu:0)] = GetDimensionSizeOp(t19, dim=0)
t_inter27: [rank=(1), shape=([1]), dtype=(int32), loc=(<class 'tripy.common.device.device'>)] = ConstantOp(data=[1])
t_inter25: [rank=(1), shape=((1,)), dtype=(int32), loc=(gpu:0)] = DynamicReshapeOp(t_inter26, t_inter27)
t_inter24: [rank=(1), dtype=(int32), loc=(gpu:0)] = ConcatenateOp(t_inter25, dim=0)
t_inter28: [rank=(1), shape=([1]), dtype=(int32), loc=(<class 'tripy.common.device.device'>)] = ConstantOp(data=[1])
t_inter23: [rank=(1), shape=([1]), dtype=(bool), loc=(gpu:0)] = CompareOp.EQ(t_inter24, t_inter28, compare_direction='EQ')
t_inter34: [rank=(1), shape=([1]), dtype=(int32), loc=(<class 'tripy.common.device.device'>)] = ConstantOp(data=[1])
t_inter35: [rank=(1), shape=(()), dtype=(int32), loc=(gpu:0)] = ConstantOp(data=<mlir_tensorrt.runtime._mlir_libs._api.MemRefValue object at 0x74a5000d0130>)
t_inter33: [rank=(1), dtype=(int32), loc=(gpu:0)] = ConcatenateOp(t_inter34, t_inter35, dim=0)
t_inter32: [rank=(1), dtype=(int32), loc=(gpu:0)] = DynamicBroadcastOp(t20, t_inter33, broadcast_dim=[])
t_inter31: [rank=(0), shape=(()), dtype=(int32), loc=(gpu:0)] = GetDimensionSizeOp(t_inter32, dim=0)
t_inter36: [rank=(1), shape=([1]), dtype=(int32), loc=(<class 'tripy.common.device.device'>)] = ConstantOp(data=[1])
t_inter30: [rank=(1), shape=((1,)), dtype=(int32), loc=(gpu:0)] = DynamicReshapeOp(t_inter31, t_inter36)
t_inter29: [rank=(1), dtype=(int32), loc=(gpu:0)] = ConcatenateOp(t_inter30, dim=0)
t_inter22: [rank=(1), shape=([1]), dtype=(int32), loc=(gpu:0)] = SelectOp(t_inter23, t_inter29, t_inter24)
t_inter21: [rank=(1), dtype=(int32), loc=(gpu:0)] = DynamicBroadcastOp(t19, t_inter22, broadcast_dim=[0])
t_inter37: [rank=(1), dtype=(int32), loc=(gpu:0)] = DynamicBroadcastOp(t_inter32, t_inter22, broadcast_dim=[0])
t21: [rank=(1), dtype=(int32), loc=(gpu:0)] = MulOp(t_inter21, t_inter37)
t22: [rank=(0), shape=(()), dtype=(int32), loc=(gpu:0)] = ConstantOp(data=1e-08)
t_inter45: [rank=(0), shape=(()), dtype=(int32), loc=(gpu:0)] = GetDimensionSizeOp(t21, dim=0)
t_inter46: [rank=(1), shape=([1]), dtype=(int32), loc=(<class 'tripy.common.device.device'>)] = ConstantOp(data=[1])
t_inter44: [rank=(1), shape=((1,)), dtype=(int32), loc=(gpu:0)] = DynamicReshapeOp(t_inter45, t_inter46)
t_inter43: [rank=(1), dtype=(int32), loc=(gpu:0)] = ConcatenateOp(t_inter44, dim=0)
t_inter47: [rank=(1), shape=([1]), dtype=(int32), loc=(<class 'tripy.common.device.device'>)] = ConstantOp(data=[1])
t_inter42: [rank=(1), shape=([1]), dtype=(bool), loc=(gpu:0)] = CompareOp.EQ(t_inter43, t_inter47, compare_direction='EQ')
t_inter53: [rank=(1), shape=([1]), dtype=(int32), loc=(<class 'tripy.common.device.device'>)] = ConstantOp(data=[1])
t_inter54: [rank=(1), shape=(()), dtype=(int32), loc=(gpu:0)] = ConstantOp(data=<mlir_tensorrt.runtime._mlir_libs._api.MemRefValue object at 0x74a500107d70>)
t_inter52: [rank=(1), dtype=(int32), loc=(gpu:0)] = ConcatenateOp(t_inter53, t_inter54, dim=0)
t_inter51: [rank=(1), dtype=(int32), loc=(gpu:0)] = DynamicBroadcastOp(t22, t_inter52, broadcast_dim=[])
t_inter50: [rank=(0), shape=(()), dtype=(int32), loc=(gpu:0)] = GetDimensionSizeOp(t_inter51, dim=0)
t_inter55: [rank=(1), shape=([1]), dtype=(int32), loc=(<class 'tripy.common.device.device'>)] = ConstantOp(data=[1])
t_inter49: [rank=(1), shape=((1,)), dtype=(int32), loc=(gpu:0)] = DynamicReshapeOp(t_inter50, t_inter55)
t_inter48: [rank=(1), dtype=(int32), loc=(gpu:0)] = ConcatenateOp(t_inter49, dim=0)
t_inter41: [rank=(1), shape=([1]), dtype=(int32), loc=(gpu:0)] = SelectOp(t_inter42, t_inter48, t_inter43)
t_inter40: [rank=(1), dtype=(int32), loc=(gpu:0)] = DynamicBroadcastOp(t21, t_inter41, broadcast_dim=[0])
t_inter56: [rank=(1), dtype=(int32), loc=(gpu:0)] = DynamicBroadcastOp(t_inter51, t_inter41, broadcast_dim=[0])
t23: [rank=(1), dtype=(int32), loc=(gpu:0)] = AddOp(t_inter40, t_inter56)
t_inter63: [rank=(0), shape=(()), dtype=(int32), loc=(gpu:0)] = GetDimensionSizeOp(t18, dim=0)
t_inter64: [rank=(1), shape=([1]), dtype=(int32), loc=(<class 'tripy.common.device.device'>)] = ConstantOp(data=[1])
t_inter62: [rank=(1), shape=((1,)), dtype=(int32), loc=(gpu:0)] = DynamicReshapeOp(t_inter63, t_inter64)
t_inter61: [rank=(1), dtype=(int32), loc=(gpu:0)] = ConcatenateOp(t_inter62, dim=0)
t_inter65: [rank=(1), shape=([1]), dtype=(int32), loc=(<class 'tripy.common.device.device'>)] = ConstantOp(data=[1])
t_inter60: [rank=(1), shape=([1]), dtype=(bool), loc=(gpu:0)] = CompareOp.EQ(t_inter61, t_inter65, compare_direction='EQ')
t_inter68: [rank=(0), shape=(()), dtype=(int32), loc=(gpu:0)] = GetDimensionSizeOp(t23, dim=0)
t_inter69: [rank=(1), shape=([1]), dtype=(int32), loc=(<class 'tripy.common.device.device'>)] = ConstantOp(data=[1])
t_inter67: [rank=(1), shape=((1,)), dtype=(int32), loc=(gpu:0)] = DynamicReshapeOp(t_inter68, t_inter69)
t_inter66: [rank=(1), dtype=(int32), loc=(gpu:0)] = ConcatenateOp(t_inter67, dim=0)
t_inter59: [rank=(1), shape=([1]), dtype=(int32), loc=(gpu:0)] = SelectOp(t_inter60, t_inter66, t_inter61)
t_inter58: [rank=(1), dtype=(int32), loc=(gpu:0)] = DynamicBroadcastOp(t18, t_inter59, broadcast_dim=[0])
t_inter70: [rank=(1), dtype=(int32), loc=(gpu:0)] = DynamicBroadcastOp(t23, t_inter59, broadcast_dim=[0])
t24: [rank=(1), dtype=(bool), loc=(gpu:0)] = CompareOp.LE(t_inter58, t_inter70, compare_direction='LE')
t_inter71: [rank=(0), shape=(()), dtype=(bool), loc=(gpu:0)] = ConstantOp(data=True)
t25: [rank=(0), dtype=(bool), loc=(gpu:0)] = ReduceOp(t24, t_inter71, reduce_mode='and', reduce_dims=[0])
outputs:
    t25: [rank=(0), dtype=(bool), loc=(gpu:0)]

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tripy/tripy/function_registry.py", line 275, in wrapper
    return self.find_overload(key, args, kwargs)(*args, **kwargs)
  File "/tripy/tripy/function_registry.py", line 179, in __call__
    return self.func(*args, **kwargs)
  File "/tripy/tripy/frontend/ops/allclose.py", line 59, in allclose
    return bool(all(compare))
  File "/tripy/tripy/frontend/tensor.py", line 241, in __bool__
    data = memref.tolist(self.eval())
  File "/tripy/tripy/frontend/tensor.py", line 183, in eval
    mlir = flat_ir.to_mlir()
  File "/tripy/tripy/flat_ir/flat_ir.py", line 153, in to_mlir
    map_error_to_user_code_and_raise(self, exc, stderr.decode())
  File "/tripy/tripy/backend/mlir/utils.py", line 458, in map_error_to_user_code_and_raise
    raise_error(
  File "/tripy/tripy/common/exception.py", line 195, in raise_error
    raise TripyException(msg) from None
tripy.common.exception.TripyException: 

--> <stdin>:1 in <module>()

TypeError: get(): incompatible function arguments. The following argument types are supported:
    1. (type: mlir_tensorrt.compiler._mlir_libs._mlir.ir.Type, value: int) -> mlir_tensorrt.compiler._mlir_libs._mlir.ir.IntegerAttr

Invoked with: IntegerType(i32), 1e-05

Additional context:
Traceback (most recent call last):
  File "/tripy/tripy/flat_ir/flat_ir.py", line 145, in to_mlir
    mlir = to_mlir_impl()
  File "/tripy/tripy/flat_ir/flat_ir.py", line 84, in to_mlir_impl
    layer_outputs = op.to_mlir(layer_inputs)
  File "/tripy/tripy/flat_ir/ops/constant.py", line 89, in to_mlir
    attr = ir.DenseElementsAttr.get(attrs=to_attrs(self.data), type=self.outputs[0].to_mlir())
  File "/tripy/tripy/flat_ir/ops/constant.py", line 83, in to_attrs
    return [mlir_utils.get_mlir_scalar_attr(out_dtype, data)]
  File "/tripy/tripy/backend/mlir/utils.py", line 89, in get_mlir_scalar_attr
    return attr_func(get_mlir_dtype(dtype), value)
TypeError: get(): incompatible function arguments. The following argument types are supported:
    1. (type: mlir_tensorrt.compiler._mlir_libs._mlir.ir.Type, value: int) -> mlir_tensorrt.compiler._mlir_libs._mlir.ir.IntegerAttr

Invoked with: IntegerType(i32), 1e-05
```

I believe that this is due to this line in `allclose.py`: `compare = abs(a - b) <= (atol + rtol * abs(b))` with the issue being `atol` and `rtol` are non-integer values and are being multiplied with an integer.

**Comment by Mgluhovskoi** [comment]
Looked into this further and this is an issue with any `__r<op>__` that mixes integers tensors and floats scalars.

```
>>> b = tp.Tensor(1,tp.int32)
>>> b+1.1
==== Trace IR ====
t75 = storage(data=1, shape=(), dtype=int32, device=gpu:0)
t76 = storage(data=1.1, shape=(), dtype=int32, device=gpu:0)
t77 = t75 + t76
outputs:
    t77: [rank=(0), dtype=(int32), loc=(gpu:0)]

==== Flat IR ====
t75: [rank=(0), shape=(()), dtype=(int32), loc=(gpu:0)] = ConstantOp(data=1)
t76: [rank=(0), shape=(()), dtype=(int32), loc=(gpu:0)] = ConstantOp(data=1.1)
t_inter6: [rank=(1), shape=(()), dtype=(int32), loc=(gpu:0)] = ConstantOp(data=<mlir_tensorrt.runtime._mlir_libs._api.MemRefValue object at 0x74a500161c30>)
t_inter7: [rank=(1), shape=([0]), dtype=(int32), loc=(<class 'tripy.common.device.device'>)] = ConstantOp(data=<mlir_tensorrt.runtime._mlir_libs._api.MemRefValue object at 0x74a500160530>)
t_inter5: [rank=(1), shape=([0]), dtype=(bool), loc=(gpu:0)] = CompareOp.EQ(t_inter6, t_inter7, compare_direction='EQ')
t_inter8: [rank=(1), shape=(()), dtype=(int32), loc=(gpu:0)] = ConstantOp(data=<mlir_tensorrt.runtime._mlir_libs._api.MemRefValue object at 0x74a5001613b0>)
t_inter4: [rank=(1), shape=([0]), dtype=(int32), loc=(gpu:0)] = SelectOp(t_inter5, t_inter8, t_inter6)
t_inter3: [rank=(0), dtype=(int32), loc=(gpu:0)] = DynamicBroadcastOp(t75, t_inter4, broadcast_dim=[])
t_inter9: [rank=(0), dtype=(int32), loc=(gpu:0)] = DynamicBroadcastOp(t76, t_inter4, broadcast_dim=[])
t77: [rank=(0), dtype=(int32), loc=(gpu:0)] = AddOp(t_inter3, t_inter9)
outputs:
    t77: [rank=(0), dtype=(int32), loc=(gpu:0)]

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tripy/tripy/frontend/tensor.py", line 219, in __repr__
    arr = self.eval()
  File "/tripy/tripy/frontend/tensor.py", line 183, in eval
    mlir = flat_ir.to_mlir()
  File "/tripy/tripy/flat_ir/flat_ir.py", line 153, in to_mlir
    map_error_to_user_code_and_raise(self, exc, stderr.decode())
  File "/tripy/tripy/backend/mlir/utils.py", line 458, in map_error_to_user_code_and_raise
    raise_error(
  File "/tripy/tripy/common/exception.py", line 195, in raise_error
    raise TripyException(msg) from None
tripy.common.exception.TripyException: 

--> <stdin>:1 in <module>()

TypeError: get(): incompatible function arguments. The following argument types are supported:
    1. (type: mlir_tensorrt.compiler._mlir_libs._mlir.ir.Type, value: int) -> mlir_tensorrt.compiler._mlir_libs._mlir.ir.IntegerAttr

Invoked with: IntegerType(i32), 1.1

Additional context:
Traceback (most recent call last):
  File "/tripy/tripy/flat_ir/flat_ir.py", line 145, in to_mlir
    mlir = to_mlir_impl()
  File "/tripy/tripy/flat_ir/flat_ir.py", line 84, in to_mlir_impl
    layer_outputs = op.to_mlir(layer_inputs)
  File "/tripy/tripy/flat_ir/ops/constant.py", line 89, in to_mlir
    attr = ir.DenseElementsAttr.get(attrs=to_attrs(self.data), type=self.outputs[0].to_mlir())
  File "/tripy/tripy/flat_ir/ops/constant.py", line 83, in to_attrs
    return [mlir_utils.get_mlir_scalar_attr(out_dtype, data)]
  File "/tripy/tripy/backend/mlir/utils.py", line 89, in get_mlir_scalar_attr
    return attr_func(get_mlir_dtype(dtype), value)
TypeError: get(): incompatible function arguments. The following argument types are supported:
    1. (type: mlir_tensorrt.compiler._mlir_libs._mlir.ir.Type, value: int) -> mlir_tensorrt.compiler._mlir_libs._mlir.ir.IntegerAttr

Invoked with: IntegerType(i32), 1.1
```

**Comment by Mgluhovskoi** [comment]
> Looked into this further and this is an issue with any `__r<op>__` that mixes integers tensors and floats scalars.
> 
> ```
> >>> b = tp.Tensor(1,tp.int32)
> >>> b+1.1
> ==== Trace IR ====
> t75 = storage(data=1, shape=(), dtype=int32, device=gpu:0)
> t76 = storage(data=1.1, shape=(), dtype=int32, device=gpu:0)
> t77 = t75 + t76
> outputs:
>     t77: [rank=(0), dtype=(int32), loc=(gpu:0)]
> 
> ==== Flat IR ====
> t75: [rank=(0), shape=(()), dtype=(int32), loc=(gpu:0)] = ConstantOp(data=1)
> t76: [rank=(0), shape=(()), dtype=(int32), loc=(gpu:0)] = ConstantOp(data=1.1)
> t_inter6: [rank=(1), shape=(()), dtype=(int32), loc=(gpu:0)] = ConstantOp(data=<mlir_tensorrt.runtime._mlir_libs._api.MemRefValue object at 0x74a500161c30>)
> t_inter7: [rank=(1), shape=([0]), dtype=(int32), loc=(<class 'tripy.common.device.device'>)] = ConstantOp(data=<mlir_tensorrt.runtime._mlir_libs._api.MemRefValue object at 0x74a500160530>)
> t_inter5: [rank=(1), shape=([0]), dtype=(bool), loc=(gpu:0)] = CompareOp.EQ(t_inter6, t_inter7, compare_direction='EQ')
> t_inter8: [rank=(1), shape=(()), dtype=(int32), loc=(gpu:0)] = ConstantOp(data=<mlir_tensorrt.runtime._mlir_libs._api.MemRefValue object at 0x74a5001613b0>)
> t_inter4: [rank=(1), shape=([0]), dtype=(int32), loc=(gpu:0)] = SelectOp(t_inter5, t_inter8, t_inter6)
> t_inter3: [rank=(0), dtype=(int32), loc=(gpu:0)] = DynamicBroadcastOp(t75, t_inter4, broadcast_dim=[])
> t_inter9: [rank=(0), dtype=(int32), loc=(gpu:0)] = DynamicBroadcastOp(t76, t_inter4, broadcast_dim=[])
> t77: [rank=(0), dtype=(int32), loc=(gpu:0)] = AddOp(t_inter3, t_inter9)
> outputs:
>     t77: [rank=(0), dtype=(int32), loc=(gpu:0)]
> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/tripy/tripy/frontend/tensor.py", line 219, in __repr__
>     arr = self.eval()
>   File "/tripy/tripy/frontend/tensor.py", line 183, in eval
>     mlir = flat_ir.to_mlir()
>   File "/tripy/tripy/flat_ir/flat_ir.py", line 153, in to_mlir
>     map_error_to_user_code_and_raise(self, exc, stderr.decode())
>   File "/tripy/tripy/backend/mlir/utils.py", line 458, in map_error_to_user_code_and_raise
>     raise_error(
>   File "/tripy/tripy/common/exception.py", line 195, in raise_error
>     raise TripyException(msg) from None
> tripy.common.exception.TripyException: 
> 
> --> <stdin>:1 in <module>()
> 
> TypeError: get(): incompatible function arguments. The following argument types are supported:
>     1. (type: mlir_tensorrt.compiler._mlir_libs._mlir.ir.Type, value: int) -> mlir_tensorrt.compiler._mlir_libs._mlir.ir.IntegerAttr
> 
> Invoked with: IntegerType(i32), 1.1
> 
> Additional context:
> Traceback (most recent call last):
>   File "/tripy/tripy/flat_ir/flat_ir.py", line 145, in to_mlir
>     mlir = to_mlir_impl()
>   File "/tripy/tripy/flat_ir/flat_ir.py", line 84, in to_mlir_impl
>     layer_outputs = op.to_mlir(layer_inputs)
>   File "/tripy/tripy/flat_ir/ops/constant.py", line 89, in to_mlir
>     attr = ir.DenseElementsAttr.get(attrs=to_attrs(self.data), type=self.outputs[0].to_mlir())
>   File "/tripy/tripy/flat_ir/ops/constant.py", line 83, in to_attrs
>     return [mlir_utils.get_mlir_scalar_attr(out_dtype, data)]
>   File "/tripy/tripy/backend/mlir/utils.py", line 89, in get_mlir_scalar_attr
>     return attr_func(get_mlir_dtype(dtype), value)
> TypeError: get(): incompatible function arguments. The following argument types are supported:
>     1. (type: mlir_tensorrt.compiler._mlir_libs._mlir.ir.Type, value: int) -> mlir_tensorrt.compiler._mlir_libs._mlir.ir.IntegerAttr
> 
> Invoked with: IntegerType(i32), 1.1
> ```

seems like `t76 = storage(data=1.1, shape=(), dtype=int32, device=gpu:0)` is invalid.

**Comment by Mgluhovskoi** [comment]
Figured out the issue and will create a new issue that better explains it and some potential fixes. Closing for now.
